###################################################################

theme = "a_transp_dracula"
# theme = "a_transp_spacebones_light"

###################################################################
[editor]
line-number = "relative"
cursorline = true
true-color = true
color-modes = true
auto-pairs = false
auto-completion = true
auto-format = true
auto-info = true
# statusline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"
# select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
newline = "all"

# [editor.soft-wrap]
# enable = true

# [editor.file-picker]
# hidden = true
# git-ignore = false

[editor.lsp]
display-messages = true
# display-inlay-hints = true

##########################################################################################################
##########################################################################################################
[keys.normal]

C-F5 = ":config-reload"
C-r = ":config-reload"
C-e = "goto_last_accessed_file"
C-s = ":update" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
C-n = "goto_next_diag"
C-p = "goto_prev_diag"

F1  = ":theme a_transp_zenburn"
F2  = ":theme a_transp_dracula"
F3  = ":theme a_transp_bogster"
F4  = ":theme a_transp_solarized_dark"
F5  = ":theme zenburn"
F6  = ":theme dracula"
F7  = ":theme bogster"
F8  = ":theme solarized_dark"
F9  = ":theme default"
F10 = ":theme spacebones_light"
F11 = ":theme bogster_light"
F12 = ":theme solarized_light"


# C-p = "goto_prev_diag"
# C-n = "goto_next_diag"
# C-q = ":sh tmux split-window -h vifm -c ':only'"

# D = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]
# G = "goto_file_end"
# # "C" = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]

# C-c = ":clipboard-yank"
# C-v = ":clipboard-paste-before"



# yank_main_selection_to_clipboard

# Quick iteration on config changes
# C-o = ":config-open"
# C-r = ":config-reload"

# Some nice Helix stuff
# C-h = "select_prev_sibling"
# C-j = "shrink_selection"
# C-k = "expand_selection"
# C-l = "select_next_sibling"


# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
# 0 = "goto_line_start"
# "$" = "goto_line_end"
# "^" = "goto_first_nonwhitespace"
"*" = [ "move_prev_word_start", "select_mode",  "move_next_word_end", "search_selection", "keep_primary_selection", "search_next" ]

G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", ":clipboard-yank", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", ":clipboard-yank", "delete_selection"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

# Clipboards over registers ye ye
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
C-v = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
# Would be nice to add ya and yi, but the surround commands can't be chained
Y = ["extend_to_line_end", ":clipboard-yank", "collapse_selection"]

# Uncanny valley stuff, this makes w and b behave as they do Vim
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

# If you want to keep the selection-while-moving behaviour of Helix, this two lines will help a lot,
# especially if you find having text remain selected while you have switched to insert or append mode
#
# There is no real difference if you have overridden the commands bound to 'w', 'e' and 'b' like above
# But if you really want to get familiar with the Helix way of selecting-while-moving, comment the
# bindings for 'w', 'e', and 'b' out and leave the bindings for 'i' and 'a' active below. A world of difference!
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

esc = ["collapse_selection", "keep_primary_selection"] # Escape the madness! No more fighting with the cursor! Or with multiple cursors!

##########################################################################################################
[keys.normal.d]

# Extend and select commands that expect a manual input can't be chained
# I've kept d[X] commands here because it's better to at least have the stuff you want to delete
# selected so that it's just a keystroke away to delete
d = ["extend_to_line_bounds", ":clipboard-yank", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", ":clipboard-yank", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", ":clipboard-yank", "delete_selection", "normal_mode"]
# down = ["select_mode", "extend_to_line_bounds", "extend_line_below", ":clipboard-yank", "delete_selection", "normal_mode"]
# up = ["select_mode", "extend_to_line_bounds", "extend_line_above", ":clipboard-yank", "delete_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", ":clipboard-yank", "delete_selection", "normal_mode"]
w = ["move_next_word_start", ":clipboard-yank", "delete_selection"]
W = ["move_next_long_word_start", ":clipboard-yank", "delete_selection"]

##########################################################################################################
[keys.normal.y]

y = ["extend_to_line_bounds", ":clipboard-yank", "normal_mode", "collapse_selection"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", ":clipboard-yank", "collapse_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", ":clipboard-yank", "collapse_selection", "normal_mode"]
# down = ["select_mode", "extend_to_line_bounds", "extend_line_below", ":clipboard-yank", "collapse_selection", "normal_mode"]
# up = ["select_mode", "extend_to_line_bounds", "extend_line_above", ":clipboard-yank", "collapse_selection", "normal_mode"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", ":clipboard-yank", "collapse_selection", "normal_mode"] }
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", ":clipboard-yank", "collapse_selection", "normal_mode"]
w = ["move_next_word_start", ":clipboard-yank", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", ":clipboard-yank", "collapse_selection", "normal_mode"]

##########################################################################################################
[keys.normal.g]
# h = "goto_first_nonwhitespace"

##########################################################################################################
[keys.normal.space]

c = "toggle_comments"
# m = "save_selection"
# "*" = [ "move_prev_word_start", "select_mode",  "move_next_word_end", "global_search", "search_next" ]

[keys.normal.space.t]
t = ":toggle-option soft-wrap.enable"
h = ":toggle-option lsp.display-inlay-hints"

##########################################################################################################
##########################################################################################################
[keys.insert]

C-F5 = [ "normal_mode", ":config-reload" ]
C-r = [ "normal_mode", ":config-reload" ]
C-e = [ "normal_mode", "goto_last_accessed_file" ]
C-s = [ "normal_mode", ":update" ]
esc = ["collapse_selection", "normal_mode"] # Escape the madness! No more fighting with the cursor! Or with multiple cursors!

# ###################################################################
# [keys.insert]
# # # j = { k = "normal_mode" } # Maps `jk` to exit insert mode


##########################################################################################################
##########################################################################################################
[keys.select]

# C-s = ":update" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
C-F5 = [ "normal_mode", ":config-reload" ]
C-r = [ "normal_mode", ":config-reload" ]
C-e = [ "normal_mode", "goto_last_accessed_file" ]
C-s = [ "normal_mode", ":update" ]

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
# 0 = "goto_line_start"
# "$" = "goto_line_end"

"*" = [ "search_selection", "keep_primary_selection", "search_next" ]
n = [ "keep_primary_selection", "search_next" ]
N = [ "keep_primary_selection", "search_prev" ]

# "^" = "goto_first_nonwhitespace"
G = "goto_file_end"
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
# "%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
# tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"
# C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = [":clipboard-yank", "delete_selection", "move_char_left"]
D = ["delete_selection", "move_char_left"]
x = ["delete_selection", "move_char_left"] #do not remember
y = [":clipboard-yank", "normal_mode", "flip_selections", "collapse_selection"]
C-c = [":clipboard-yank", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", ":clipboard-yank", "goto_line_start", "collapse_selection", "normal_mode"]
p = [ ":clipboard-paste-before", ":clipboard-yank", "delete_selection", "normal_mode", "move_char_left" ]
P = [ ":clipboard-paste-replace", "collapse_selection", "normal_mode" ] #do not remember
C-v = [ ":clipboard-paste-replace", "collapse_selection", "normal_mode" ] #do not remember

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"] # Escape the madness! No more fighting with the cursor! Or with multiple cursors!

###################################################################
[keys.select.space]
c = "toggle_comments"
